# Generated by Django 3.0.6 on 2020-05-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(help_text='Enter authors first name', max_length=255)),
                ('author_last_name', models.CharField(max_length=255)),
                ('author_dob', models.DateField(null=True)),
                ('author_dod', models.DateField(null=True)),
                ('author_bio', models.TextField(max_length=255)),
                ('author_nationality', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(help_text='Enter book title', max_length=255)),
                ('book_isbn', models.BigIntegerField(blank=True, null=True)),
                ('book_year', models.IntegerField(blank=True, null=True)),
                ('book_genre', models.CharField(max_length=255)),
                ('book_description', models.TextField(max_length=255)),
                ('book_author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookAuthor')),
            ],
        ),
    ]
