# Generated by Django 3.0.6 on 2020-05-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200509_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='list_book',
        ),
        migrations.AddField(
            model_name='booklist',
            name='list_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
