# Generated by Django 3.0.6 on 2020-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200509_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='list_book',
        ),
        migrations.AddField(
            model_name='book',
            name='book_list',
            field=models.ManyToManyField(to='books.BookList'),
        ),
    ]
