# Generated by Django 3.0.6 on 2020-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200509_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_list',
            field=models.ManyToManyField(help_text='Select a list for this book', null=True, to='books.BookList'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='list_title',
            field=models.CharField(max_length=255),
        ),
    ]
