# Generated by Django 3.0.6 on 2020-05-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200509_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_list',
        ),
    ]
