# Generated by Django 3.0.6 on 2020-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_book_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='list_books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
