# Generated by Django 3.0.6 on 2020-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_bookreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='review_scores',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='review_score',
            field=models.IntegerField(null=True),
        ),
    ]
