# Generated by Django 3.0.6 on 2020-05-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200513_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
