# Generated by Django 3.0.6 on 2020-05-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200513_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
