# Generated by Django 3.0.6 on 2020-05-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20200516_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together=set(),
        ),
    ]
