# Generated by Django 3.0.6 on 2020-05-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
