# Generated by Django 3.0.6 on 2020-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='radi_provera',
            field=models.CharField(default=1, help_text='Enter yes or no', max_length=20),
            preserve_default=False,
        ),
    ]
