# Generated by Django 3.0.6 on 2020-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_radi_provera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='radi_provera',
            field=models.CharField(help_text='Enter yes or no', max_length=20, null=True),
        ),
    ]
