# Generated by Django 3.0.6 on 2020-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200519_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='radi_provera',
            field=models.CharField(blank=True, help_text='Enter yes or no', max_length=20, null=True),
        ),
    ]
