# Generated by Django 3.0.6 on 2020-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200519_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='radi_provera',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='Enter your location', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
